### PR TITLE
fix the pattern for dnsaddrs

### PR DESCRIPTION
**Pull request by marten-seemann**
Closes #15.

This implements the opposite logic of #15.

### CODE REVIEW

**Comment by Stebalien** [comment]
We're going to need to do a quick audit of uses to make sure this doesn't accidentally break something. I doubt there is sufficient test coverage, unfortunately.

**Comment by BigLep** [comment]
@marten-seemann : following up from our triage on 2021-05-17, we wanted to make sure you saw this comment.

**Comment by marten-seemann** [comment]
Sorry, I think I missed the conclusion of that discussion. I'm not sure how to proceed here.

**Comment by Stebalien** [comment]
I'd like to shelve this for a few weeks. What we have now is working so I'd rather not touch this till we've had a chance to look at every _use_ of these patterns to make sure we're not breaking anything.

**Comment by marten-seemann** [comment]
Should we disable the test case then? We need to deflake it if we want to roll out the Unified CI Setup?

**Comment by Stebalien** [comment]
Let's make it test what we have.

**Comment by marten-seemann** [comment]
Closing, as we merged #18.

**Pull request closed without merging**
